services:

  waha:
      image: devlikeapro/waha:latest
      container_name: wpp_bot_ConstituicaoAI
      restart: always

      ports:
        - '3000:3000'
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: wpp_bot_api_ConstituicaoAI
    ports:
      - '5000:5000'
